# frozen_string_literal: true

# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V19
        module Enums
          # Container for enum describing the type of asset automation.
          class AssetAutomationTypeEnum
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods

            # The type of asset automation.
            module AssetAutomationType
              # Not specified.
              UNSPECIFIED = 0

              # Used as a return value only. Represents value unknown in this version.
              UNKNOWN = 1

              # Text asset automation includes headlines and descriptions.
              # By default, advertisers are opted-in for Performance Max and
              # opted-out for Search.
              TEXT_ASSET_AUTOMATION = 2

              # Converts horizontal video assets to vertical orientation using
              # content-aware technology. By default, advertisers are opted in for
              # DemandGenVideoResponsiveAd.
              GENERATE_VERTICAL_YOUTUBE_VIDEOS = 3

              # Shortens video assets to better capture user attention using
              # content-aware technology. By default, advertisers are opted in for
              # DemandGenVideoResponsiveAd.
              GENERATE_SHORTER_YOUTUBE_VIDEOS = 4

              # Generates a preview of the landing page shown in the engagement panel.
              #
              # By using this feature, you confirm that you own all legal rights to the
              # images on the landing page used by this account (or you have permission
              # to share the images with Google). You hereby instruct Google to publish
              # these images on your behalf for advertising or other commercial purposes.
              GENERATE_LANDING_PAGE_PREVIEW = 5

              # Generates video enhancements (vertical and shorter videos) for PMax
              # campaigns. Opted in by default.
              GENERATE_ENHANCED_YOUTUBE_VIDEOS = 6
            end
          end
        end
      end
    end
  end
end
