source "https://rubygems.org"

gemspec

gem "google-style", "~> 1.27.0"
gem "minitest", "~> 5.16"
gem "minitest-autotest", "~> 1.0"
gem "minitest-focus", "~> 1.1"
gem "minitest-rg", "~> 5.2"
gem "redcarpet", "~> 3.0"
gem "yard", "~> 0.9"
