# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Showcase
    module V1beta1
      module Messaging
        # Path helper methods for the Messaging API.
        module Paths
          ##
          # Create a fully-qualified Blurb resource string.
          #
          # @overload blurb_path(user:, legacy_user:, blurb:)
          #   The resource will be in the following format:
          #
          #   `users/{user}/profile/blurbs/legacy/{legacy_user}~{blurb}`
          #
          #   @param user [String]
          #   @param legacy_user [String]
          #   @param blurb [String]
          #
          # @overload blurb_path(user:, blurb:)
          #   The resource will be in the following format:
          #
          #   `users/{user}/profile/blurbs/{blurb}`
          #
          #   @param user [String]
          #   @param blurb [String]
          #
          # @overload blurb_path(room:, blurb:)
          #   The resource will be in the following format:
          #
          #   `rooms/{room}/blurbs/{blurb}`
          #
          #   @param room [String]
          #   @param blurb [String]
          #
          # @overload blurb_path(room:, legacy_room:, blurb:)
          #   The resource will be in the following format:
          #
          #   `rooms/{room}/blurbs/legacy/{legacy_room}.{blurb}`
          #
          #   @param room [String]
          #   @param legacy_room [String]
          #   @param blurb [String]
          #
          # @return [::String]
          def blurb_path **args
            resources = {
              "blurb:legacy_user:user" => (proc do |user:, legacy_user:, blurb:|
                raise ::ArgumentError, "user cannot contain /" if user.to_s.include? "/"
                raise ::ArgumentError, "legacy_user cannot contain /" if legacy_user.to_s.include? "/"

                "users/#{user}/profile/blurbs/legacy/#{legacy_user}~#{blurb}"
              end),
              "blurb:user" => (proc do |user:, blurb:|
                raise ::ArgumentError, "user cannot contain /" if user.to_s.include? "/"

                "users/#{user}/profile/blurbs/#{blurb}"
              end),
              "blurb:room" => (proc do |room:, blurb:|
                raise ::ArgumentError, "room cannot contain /" if room.to_s.include? "/"

                "rooms/#{room}/blurbs/#{blurb}"
              end),
              "blurb:legacy_room:room" => (proc do |room:, legacy_room:, blurb:|
                raise ::ArgumentError, "room cannot contain /" if room.to_s.include? "/"
                raise ::ArgumentError, "legacy_room cannot contain /" if legacy_room.to_s.include? "/"

                "rooms/#{room}/blurbs/legacy/#{legacy_room}.#{blurb}"
              end)
            }

            resource = resources[args.keys.sort.join(":")]
            raise ::ArgumentError, "no resource found for values #{args.keys}" if resource.nil?
            resource.call(**args)
          end

          ##
          # Create a fully-qualified Room resource string.
          #
          # The resource will be in the following format:
          #
          # `rooms/{room}`
          #
          # @param room [String]
          #
          # @return [::String]
          def room_path room:
            "rooms/#{room}"
          end

          ##
          # Create a fully-qualified User resource string.
          #
          # The resource will be in the following format:
          #
          # `users/{user}`
          #
          # @param user [String]
          #
          # @return [::String]
          def user_path user:
            "users/#{user}"
          end

          extend self
        end
      end
    end
  end
end
