# frozen_string_literal: true

# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V25
        module Services
          module YouTubeVideoUploadService
            ##
            # Resumable upload stub for the YouTubeVideoUploadService service.
            #
            # Owns the REST client stub the uploads are performed through, the transcoders that build their
            # initiation requests, and the credentials error that a client unable to perform REST calls has to
            # raise when an upload is attempted.
            #
            # @private
            #
            class ResumableUploadStub
              # @private
              CREATE_YOU_TUBE_VIDEO_UPLOAD_URL_PREFIX = "resumable/upload"

              # @private
              def initialize endpoint:, endpoint_template:, universe_domain:, credentials:, logger:
                # These require statements are intentionally placed here to initialize
                # the REST modules only when it's required.
                require "gapic/rest"

                # Uploads travel over REST, and credentials cannot be recovered from a gRPC channel. Rather than
                # raise while a client is being constructed, which would break every other method on it, the
                # error is stored and raised when an upload is actually attempted.
                if defined?(::GRPC::Core::Channel) &&
                   (credentials.is_a?(::GRPC::Core::Channel) || credentials.is_a?(::GRPC::Core::ChannelCredentials))
                  @credentials_error = ::ArgumentError.new(
                    "Resumable uploads are performed over REST and cannot use a gRPC channel as credentials, " \
                    "because credentials cannot be recovered from a channel. Construct the client with Google " \
                    "OAuth credentials (a keyfile path, a Hash, or a Google::Auth::Credentials instance) to use " \
                    "resumable upload methods."
                  )
                  return
                end

                @client_stub = ::Gapic::Rest::ClientStub.new endpoint: endpoint,
                                                             endpoint_template: endpoint_template,
                                                             universe_domain: universe_domain,
                                                             credentials: credentials,
                                                             numeric_enums: false,
                                                             service_name: self.class,
                                                             raise_faraday_errors: false,
                                                             logger: logger
              end

              ##
              # @private
              #
              # The REST client stub the uploads are performed through.
              #
              # @return [::Gapic::Rest::ClientStub]
              #
              # @raise [::ArgumentError] if this client cannot perform REST calls.
              #
              def client_stub
                raise @credentials_error if @credentials_error
                @client_stub
              end

              ##
              # @private
              #
              # GRPC transcoding helper method for the create_you_tube_video_upload resumable upload initiation request.
              #
              # The upload itself is not transcoded: only the request that creates the upload session is, and the
              # verb is discarded because initiation is always a POST. Query string parameters are folded into the
              # URL, since the upload sends the initiation request with no separate parameters.
              #
              # @param request_pb [::Google::Ads::GoogleAds::V25::Services::CreateYouTubeVideoUploadRequest]
              #   A request object representing the call parameters. Required.
              # @return [Array(String, [String, nil])]
              #   Uri, Body
              def self.transcode_create_you_tube_video_upload_request request_pb
                transcoder = ::Gapic::Rest::GrpcTranscoder.new
                                                          .with_bindings(
                                                            uri_method: :post,
                                                            uri_template: "/v25/customers/{customer_id}/youTubeVideoUploads:create",
                                                            body: "*",
                                                            matches: [
                                                              ["customer_id", %r{^[^/]+/?$}, false]
                                                            ]
                                                          )
                _verb, uri, query_string_params, body = transcoder.transcode request_pb
                uri = "/#{CREATE_YOU_TUBE_VIDEO_UPLOAD_URL_PREFIX}#{uri}"
                uri = "#{uri}?#{query_string_params.join '&'}" if query_string_params.any?
                [uri, body]
              end
            end
          end
        end
      end
    end
  end
end
