# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
      - image: gcr.io/gapic-showcase/gapic-showcase:0.0.12
    working_directory: ~/gapic-generator-ruby
    steps:
      - checkout
      - run:
          name: checkout submodules
          command: git submodule update --init --recursive
      - restore_cache:
          keys:
            - v1-dependencies-generator
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3
            cd shared && bundle install --jobs=4 --retry=3
            cd ../gapic-generator && bundle install --jobs=4 --retry=3
            cd ../gapic-generator-cloud && bundle install --jobs=4 --retry=3
            bundle clean
      - save_cache:
          paths:
            - ~/.bundle
          key: v1-dependencies-generator
      - run:
          name: wait for showcase server
          command: dockerize -wait tcp://localhost:7469 -timeout 1m
      - run:
          name: run tests
          command: bundle exec rake ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
