# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.1
      - image: gcr.io/gapic-images/gapic-showcase:0.5.0
    working_directory: ~/gapic-generator-ruby
    steps:
      - checkout
      - run:
          name: update environment
          command: |
            gem update --system
            gem install bundler
      - run:
          name: checkout submodules
          command: git submodule update --init --recursive
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3
            cd shared && bundle install --jobs=4 --retry=3
            cd ../gapic-generator && bundle install --jobs=4 --retry=3
            cd ../gapic-generator-cloud && bundle install --jobs=4 --retry=3
            cd ..
      - run:
          name: wait for showcase server
          command: dockerize -wait tcp://localhost:7469 -timeout 1m
      - run:
          name: run tests
          command: bundle exec rake update ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
