# frozen_string_literal: true

# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V21
        module Common
          # Container for Customer level third party integration partners.
          # @!attribute [rw] viewability_integration_partners
          #   @return [::Array<::Google::Ads::GoogleAds::V21::Common::CustomerThirdPartyViewabilityIntegrationPartner>]
          #     Allowed third party integration partners for YouTube viewability
          #     verification.
          # @!attribute [rw] brand_lift_integration_partners
          #   @return [::Array<::Google::Ads::GoogleAds::V21::Common::CustomerThirdPartyBrandLiftIntegrationPartner>]
          #     Allowed third party integration partners for Brand Lift verification.
          # @!attribute [rw] brand_safety_integration_partners
          #   @return [::Array<::Google::Ads::GoogleAds::V21::Common::CustomerThirdPartyBrandSafetyIntegrationPartner>]
          #     Allowed third party integration partners for brand safety verification.
          # @!attribute [rw] reach_integration_partners
          #   @return [::Array<::Google::Ads::GoogleAds::V21::Common::CustomerThirdPartyReachIntegrationPartner>]
          #     Allowed third party integration partners for reach verification.
          class CustomerThirdPartyIntegrationPartners
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Container for third party viewability integration data for Customer.
          # @!attribute [rw] viewability_integration_partner
          #   @return [::Google::Ads::GoogleAds::V21::Enums::ThirdPartyViewabilityIntegrationPartnerEnum::ThirdPartyViewabilityIntegrationPartner]
          #     Allowed third party integration partners for YouTube viewability
          #     verification.
          # @!attribute [rw] allow_share_cost
          #   @return [::Boolean]
          #     If true, cost data can be shared with this vendor.
          class CustomerThirdPartyViewabilityIntegrationPartner
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Container for third party brand safety integration data for Customer.
          # @!attribute [rw] brand_safety_integration_partner
          #   @return [::Google::Ads::GoogleAds::V21::Enums::ThirdPartyBrandSafetyIntegrationPartnerEnum::ThirdPartyBrandSafetyIntegrationPartner]
          #     Allowed third party integration partners for brand safety verification.
          class CustomerThirdPartyBrandSafetyIntegrationPartner
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Container for third party Brand Lift integration data for Customer.
          # @!attribute [rw] brand_lift_integration_partner
          #   @return [::Google::Ads::GoogleAds::V21::Enums::ThirdPartyBrandLiftIntegrationPartnerEnum::ThirdPartyBrandLiftIntegrationPartner]
          #     Allowed Third Party integration partners for Brand Lift verification.
          # @!attribute [rw] allow_share_cost
          #   @return [::Boolean]
          #     If true, cost data can be shared with this vendor.
          class CustomerThirdPartyBrandLiftIntegrationPartner
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Container for third party reach integration data for Customer.
          # @!attribute [rw] reach_integration_partner
          #   @return [::Google::Ads::GoogleAds::V21::Enums::ThirdPartyReachIntegrationPartnerEnum::ThirdPartyReachIntegrationPartner]
          #     Allowed Third Party integration partners for reach verification.
          # @!attribute [rw] allow_share_cost
          #   @return [::Boolean]
          #     If true, cost data can be shared with this vendor.
          class CustomerThirdPartyReachIntegrationPartner
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Container for Campaign level third party integration partners.
          # @!attribute [rw] viewability_integration_partners
          #   @return [::Array<::Google::Ads::GoogleAds::V21::Common::CampaignThirdPartyViewabilityIntegrationPartner>]
          #     Third party integration partners for YouTube viewability
          #     verification for this Campaign.
          # @!attribute [rw] brand_lift_integration_partners
          #   @return [::Array<::Google::Ads::GoogleAds::V21::Common::CampaignThirdPartyBrandLiftIntegrationPartner>]
          #     Third party integration partners for Brand Lift verification for this
          #     Campaign.
          # @!attribute [rw] brand_safety_integration_partners
          #   @return [::Array<::Google::Ads::GoogleAds::V21::Common::CampaignThirdPartyBrandSafetyIntegrationPartner>]
          #     Third party integration partners for brand safety verification for this
          #     Campaign.
          # @!attribute [rw] reach_integration_partners
          #   @return [::Array<::Google::Ads::GoogleAds::V21::Common::CampaignThirdPartyReachIntegrationPartner>]
          #     Third party integration partners for reach verification for this Campaign.
          class CampaignThirdPartyIntegrationPartners
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Container for third party viewability integration data for Campaign.
          # @!attribute [rw] viewability_integration_partner
          #   @return [::Google::Ads::GoogleAds::V21::Enums::ThirdPartyViewabilityIntegrationPartnerEnum::ThirdPartyViewabilityIntegrationPartner]
          #     Allowed third party integration partners for YouTube viewability
          #     verification.
          # @!attribute [rw] viewability_integration_partner_data
          #   @return [::Google::Ads::GoogleAds::V21::Common::ThirdPartyIntegrationPartnerData]
          #     Third party partner data for YouTube viewability verification. This is
          #     optional metadata for partners to join or attach data to Ads campaigns.
          # @!attribute [rw] share_cost
          #   @return [::Boolean]
          #     If true, then cost data will be shared with this vendor.
          class CampaignThirdPartyViewabilityIntegrationPartner
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Container for third party brand safety integration data for Campaign.
          # @!attribute [rw] brand_safety_integration_partner
          #   @return [::Google::Ads::GoogleAds::V21::Enums::ThirdPartyBrandSafetyIntegrationPartnerEnum::ThirdPartyBrandSafetyIntegrationPartner]
          #     Allowed third party integration partners for brand safety verification.
          # @!attribute [rw] brand_safety_integration_partner_data
          #   @return [::Google::Ads::GoogleAds::V21::Common::ThirdPartyIntegrationPartnerData]
          #     Third party partner data for YouTube brand safety verification. This is
          #     optional metadata for partners to join or attach data to Ads campaigns.
          class CampaignThirdPartyBrandSafetyIntegrationPartner
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Container for third party Brand Lift integration data for Campaign.
          # @!attribute [rw] brand_lift_integration_partner
          #   @return [::Google::Ads::GoogleAds::V21::Enums::ThirdPartyBrandLiftIntegrationPartnerEnum::ThirdPartyBrandLiftIntegrationPartner]
          #     Allowed third party integration partners for Brand Lift verification.
          # @!attribute [rw] brand_lift_integration_partner_data
          #   @return [::Google::Ads::GoogleAds::V21::Common::ThirdPartyIntegrationPartnerData]
          #     Third party partner data for YouTube Brand Lift verification. This is
          #     optional metadata for partners to join or attach data to Ads campaigns.
          # @!attribute [rw] share_cost
          #   @return [::Boolean]
          #     If true, then cost data will be shared with this vendor.
          class CampaignThirdPartyBrandLiftIntegrationPartner
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Container for third party reach integration data for Campaign.
          # @!attribute [rw] reach_integration_partner
          #   @return [::Google::Ads::GoogleAds::V21::Enums::ThirdPartyReachIntegrationPartnerEnum::ThirdPartyReachIntegrationPartner]
          #     Allowed third party integration partners for reach verification.
          # @!attribute [rw] reach_integration_partner_data
          #   @return [::Google::Ads::GoogleAds::V21::Common::ThirdPartyIntegrationPartnerData]
          #     Third party partner data for YouTube Reach verification. This is
          #     optional metadata for partners to join or attach data to Ads campaigns.
          # @!attribute [rw] share_cost
          #   @return [::Boolean]
          #     If true, then cost data will be shared with this vendor.
          class CampaignThirdPartyReachIntegrationPartner
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Contains third party measurement partner related data for video campaigns.
          # @!attribute [rw] client_id
          #   @return [::String]
          #     The client ID that allows the measurement partner to join multiple
          #     campaigns for a particular advertiser.
          # @!attribute [rw] third_party_placement_id
          #   @return [::String]
          #     The third party placement ID that maps the measurement partner data with a
          #     campaign (or a group of related campaigns) specific data.
          class ThirdPartyIntegrationPartnerData
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
