# frozen_string_literal: true

# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V25
        module Resources
          # A campaign.
          # @!attribute [rw] resource_name
          #   @return [::String]
          #     Immutable. The resource name of the campaign.
          #     Campaign resource names have the form:
          #
          #     `customers/{customer_id}/campaigns/{campaign_id}`
          # @!attribute [r] id
          #   @return [::Integer]
          #     Output only. The ID of the campaign.
          # @!attribute [rw] name
          #   @return [::String]
          #     The name of the campaign.
          #
          #     This field is required and should not be empty when creating new
          #     campaigns.
          #
          #     It must not contain any null (code point 0x0), NL line feed
          #     (code point 0xA) or carriage return (code point 0xD) characters.
          # @!attribute [r] primary_status
          #   @return [::Google::Ads::GoogleAds::V25::Enums::CampaignPrimaryStatusEnum::CampaignPrimaryStatus]
          #     Output only. The primary status of the campaign.
          #
          #     Provides insight into why a campaign is not serving or not serving
          #     optimally. Modification to the campaign and its related entities might take
          #     a while to be reflected in this status.
          # @!attribute [r] primary_status_reasons
          #   @return [::Array<::Google::Ads::GoogleAds::V25::Enums::CampaignPrimaryStatusReasonEnum::CampaignPrimaryStatusReason>]
          #     Output only. The primary status reasons of the campaign.
          #
          #     Provides insight into why a campaign is not serving or not serving
          #     optimally. These reasons are aggregated to determine an overall
          #     CampaignPrimaryStatus.
          # @!attribute [rw] status
          #   @return [::Google::Ads::GoogleAds::V25::Enums::CampaignStatusEnum::CampaignStatus]
          #     The status of the campaign.
          #
          #     When a new campaign is added, the status defaults to ENABLED.
          # @!attribute [r] serving_status
          #   @return [::Google::Ads::GoogleAds::V25::Enums::CampaignServingStatusEnum::CampaignServingStatus]
          #     Output only. The ad serving status of the campaign.
          # @!attribute [r] bidding_strategy_system_status
          #   @return [::Google::Ads::GoogleAds::V25::Enums::BiddingStrategySystemStatusEnum::BiddingStrategySystemStatus]
          #     Output only. The system status of the campaign's bidding strategy.
          # @!attribute [rw] ad_serving_optimization_status
          #   @return [::Google::Ads::GoogleAds::V25::Enums::AdServingOptimizationStatusEnum::AdServingOptimizationStatus]
          #     The ad serving optimization status of the campaign.
          # @!attribute [rw] advertising_channel_type
          #   @return [::Google::Ads::GoogleAds::V25::Enums::AdvertisingChannelTypeEnum::AdvertisingChannelType]
          #     Immutable. The primary serving target for ads within the campaign.
          #     The targeting options can be refined in `network_settings`.
          #
          #     This field is required and should not be empty when creating new
          #     campaigns.
          #
          #     Can be set only when creating campaigns.
          #     After the campaign is created, the field can not be changed.
          # @!attribute [rw] advertising_channel_sub_type
          #   @return [::Google::Ads::GoogleAds::V25::Enums::AdvertisingChannelSubTypeEnum::AdvertisingChannelSubType]
          #     Immutable. Optional refinement to `advertising_channel_type`.
          #     Must be a valid sub-type of the parent channel type.
          #
          #     Can be set only when creating campaigns.
          #     After campaign is created, the field can not be changed.
          # @!attribute [rw] tracking_url_template
          #   @return [::String]
          #     The URL template for constructing a tracking URL.
          # @!attribute [rw] url_custom_parameters
          #   @return [::Array<::Google::Ads::GoogleAds::V25::Common::CustomParameter>]
          #     The list of mappings used to substitute custom parameter tags in a
          #     `tracking_url_template`, `final_urls`, or `mobile_final_urls`.
          # @!attribute [rw] local_services_campaign_settings
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::LocalServicesCampaignSettings]
          #     The Local Services Campaign related settings.
          # @!attribute [rw] travel_campaign_settings
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::TravelCampaignSettings]
          #     Settings for Travel campaign.
          # @!attribute [rw] demand_gen_campaign_settings
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::DemandGenCampaignSettings]
          #     Settings for Demand Gen campaign.
          # @!attribute [rw] video_campaign_settings
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::VideoCampaignSettings]
          #     Settings for Video campaign.
          # @!attribute [rw] pmax_campaign_settings
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::PmaxCampaignSettings]
          #     Settings for Performance Max campaign.
          # @!attribute [rw] real_time_bidding_setting
          #   @return [::Google::Ads::GoogleAds::V25::Common::RealTimeBiddingSetting]
          #     Settings for Real-Time Bidding, a feature only available for campaigns
          #     targeting the Ad Exchange network.
          # @!attribute [rw] network_settings
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::NetworkSettings]
          #     The network settings for the campaign.
          # @!attribute [rw] hotel_setting
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::HotelSettingInfo]
          #     The hotel setting for the campaign.
          # @!attribute [rw] dynamic_search_ads_setting
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::DynamicSearchAdsSetting]
          #     The setting for controlling Dynamic Search Ads (DSA).
          # @!attribute [rw] shopping_setting
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::ShoppingSetting]
          #     The setting for controlling Shopping campaigns.
          # @!attribute [rw] targeting_setting
          #   @return [::Google::Ads::GoogleAds::V25::Common::TargetingSetting]
          #     Setting for targeting related features.
          # @!attribute [rw] audience_setting
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::AudienceSetting]
          #     Immutable. Setting for audience related features.
          # @!attribute [rw] geo_target_type_setting
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::GeoTargetTypeSetting]
          #     The setting for ads geotargeting.
          # @!attribute [rw] local_campaign_setting
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::LocalCampaignSetting]
          #     The setting for local campaign.
          # @!attribute [rw] app_campaign_setting
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::AppCampaignSetting]
          #     The setting related to App Campaign.
          # @!attribute [r] labels
          #   @return [::Array<::String>]
          #     Output only. The resource names of labels attached to this campaign.
          # @!attribute [r] experiment_type
          #   @return [::Google::Ads::GoogleAds::V25::Enums::CampaignExperimentTypeEnum::CampaignExperimentType]
          #     Output only. The type of campaign: normal, draft, or experiment.
          # @!attribute [r] base_campaign
          #   @return [::String]
          #     Output only. The resource name of the base campaign of a draft or
          #     experiment campaign. For base campaigns, this is equal to `resource_name`.
          #
          #     This field is read-only.
          # @!attribute [rw] campaign_budget
          #   @return [::String]
          #     The resource name of the campaign budget of the campaign.
          # @!attribute [r] bidding_strategy_type
          #   @return [::Google::Ads::GoogleAds::V25::Enums::BiddingStrategyTypeEnum::BiddingStrategyType]
          #     Output only. The type of bidding strategy.
          #
          #     A bidding strategy can be created by setting either the bidding scheme to
          #     create a standard bidding strategy or the `bidding_strategy` field to
          #     create a portfolio bidding strategy.
          #
          #     This field is read-only.
          # @!attribute [r] accessible_bidding_strategy
          #   @return [::String]
          #     Output only. Resource name of AccessibleBiddingStrategy, a read-only view
          #     of the unrestricted attributes of the attached portfolio bidding strategy
          #     identified by 'bidding_strategy'. Empty, if the campaign does not use a
          #     portfolio strategy. Unrestricted strategy attributes are available to all
          #     customers with whom the strategy is shared and are read from the
          #     AccessibleBiddingStrategy resource. In contrast, restricted attributes are
          #     only available to the owner customer of the strategy and their managers.
          #     Restricted attributes can only be read from the BiddingStrategy resource.
          # @!attribute [rw] campaign_group
          #   @return [::String]
          #     The resource name of the campaign group that this campaign belongs to.
          # @!attribute [rw] start_date_time
          #   @return [::String]
          #     The date and time when campaign started in serving. The timestamp is in
          #     the customer's time zone and in "yyyy-MM-dd HH:mm:ss" format. Set the time
          #     component to 00:00:00 for daily granularity, time granularity is only
          #     supported for some campaign types.
          # @!attribute [rw] end_date_time
          #   @return [::String]
          #     The last day and time of the campaign in serving customer's timezone in
          #     "yyyy-MM-dd HH:mm:ss" format. Set the time component to 23:59:59 for daily
          #     granularity, time granularity is only supported for some campaign types. On
          #     create, defaults to running indefinitely. To set an existing campaign to
          #     run indefinitely, clear this field.
          # @!attribute [rw] final_url_suffix
          #   @return [::String]
          #     Suffix used to append query parameters to landing pages that are served
          #     with parallel tracking.
          # @!attribute [rw] frequency_caps
          #   @return [::Array<::Google::Ads::GoogleAds::V25::Common::FrequencyCapEntry>]
          #     A list that limits how often each user will see this campaign's ads.
          # @!attribute [rw] vanity_pharma
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::VanityPharma]
          #     Describes how unbranded pharma ads will be displayed.
          # @!attribute [rw] selective_optimization
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::SelectiveOptimization]
          #     Selective optimization setting for this campaign, which includes a set of
          #     conversion actions to optimize this campaign towards.
          #     This feature only applies to app campaigns that use MULTI_CHANNEL as
          #     AdvertisingChannelType and APP_CAMPAIGN or APP_CAMPAIGN_FOR_ENGAGEMENT as
          #     AdvertisingChannelSubType.
          # @!attribute [rw] optimization_goal_setting
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::OptimizationGoalSetting]
          #     Optimization goal setting for this campaign, which includes a set of
          #     optimization goal types.
          # @!attribute [r] tracking_setting
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::TrackingSetting]
          #     Output only. Campaign-level settings for tracking information.
          # @!attribute [rw] payment_mode
          #   @return [::Google::Ads::GoogleAds::V25::Enums::PaymentModeEnum::PaymentMode]
          #     Payment mode for the campaign.
          # @!attribute [r] optimization_score
          #   @return [::Float]
          #     Output only. Optimization score of the campaign.
          #
          #     Optimization score is an estimate of how well a campaign is set to perform.
          #     It ranges from 0% (0.0) to 100% (1.0), with 100% indicating that the
          #     campaign is performing at full potential. This field is null for unscored
          #     campaigns.
          #
          #     See "About optimization score" at
          #     https://support.google.com/google-ads/answer/9061546.
          #
          #     This field is read-only.
          # @!attribute [rw] excluded_parent_asset_field_types
          #   @return [::Array<::Google::Ads::GoogleAds::V25::Enums::AssetFieldTypeEnum::AssetFieldType>]
          #     The asset field types that should be excluded from this campaign. Asset
          #     links with these field types will not be inherited by this campaign from
          #     the upper level.
          # @!attribute [rw] excluded_parent_asset_set_types
          #   @return [::Array<::Google::Ads::GoogleAds::V25::Enums::AssetSetTypeEnum::AssetSetType>]
          #     The asset set types that should be excluded from this campaign. Asset set
          #     links with these types will not be inherited by this campaign from
          #     the upper level.
          #     Location group types (GMB_DYNAMIC_LOCATION_GROUP,
          #     CHAIN_DYNAMIC_LOCATION_GROUP, and STATIC_LOCATION_GROUP) are child types of
          #     LOCATION_SYNC. Therefore, if LOCATION_SYNC is set for this field, all
          #     location group asset sets are not allowed to be linked to this campaign,
          #     and all Location Extension (LE) and Affiliate Location Extensions (ALE)
          #     will not be served under this campaign.
          #     Only LOCATION_SYNC is currently supported.
          # @!attribute [r] performance_max_upgrade
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::PerformanceMaxUpgrade]
          #     Output only. Information about campaigns being upgraded to Performance Max.
          # @!attribute [rw] hotel_property_asset_set
          #   @return [::String]
          #     Immutable. The resource name for a set of hotel properties for Performance
          #     Max for travel goals campaigns.
          # @!attribute [rw] listing_type
          #   @return [::Google::Ads::GoogleAds::V25::Enums::ListingTypeEnum::ListingType]
          #     Immutable. Listing type of ads served for this campaign.
          #     Field is restricted for usage with Performance Max campaigns.
          # @!attribute [rw] asset_automation_settings
          #   @return [::Array<::Google::Ads::GoogleAds::V25::Resources::Campaign::AssetAutomationSetting>]
          #     Contains the opt-in/out status of each AssetAutomationType.
          #     See documentation of each asset automation type enum for default
          #     opt in/out behavior.
          # @!attribute [rw] keyword_match_type
          #   @return [::Google::Ads::GoogleAds::V25::Enums::CampaignKeywordMatchTypeEnum::CampaignKeywordMatchType]
          #     Keyword match type of Campaign. Set to BROAD to set broad matching for all
          #     keywords in a campaign.
          # @!attribute [rw] brand_guidelines_enabled
          #   @return [::Boolean]
          #     Immutable. Whether Brand Guidelines are enabled for this Campaign.
          #     Only applicable to Performance Max campaigns. If enabled, business name
          #     and logo assets must be linked as CampaignAssets instead of
          #     AssetGroupAssets.
          #
          #     Writable only at campaign creation. Set to true to enable Brand
          #     Guidelines when creating a new Performance Max campaign.
          #
          #     Immutable after creation. This field cannot be modified using standard
          #     update operations after the campaign has been created.
          #
          #     For existing campaigns: To enable Brand Guidelines on a campaign after it
          #     has been created, use the CampaignService.EnablePMaxBrandGuidelines method,
          #     which is a separate operation. It is not possible to disable Brand
          #     Guidelines for an existing campaign.
          #
          #     Incompatible with Travel Goals: This feature is not supported for
          #     Performance Max campaigns with Travel Goals. Attempting to set this field
          #     to true for a Travel Goals campaign will result in an error.
          # @!attribute [rw] brand_guidelines
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::BrandGuidelines]
          #     These settings control how your brand appears in automatically generated
          #     assets and formats within this campaign. Note: These settings can only be
          #     used for Performance Max campaigns that have Brand Guidelines enabled.
          # @!attribute [rw] text_guidelines
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::TextGuidelines]
          #     Settings to control automatically generated text assets. Only available
          #     in Performance Max and Search campaigns (Brand Guidelines does not need
          #     to be enabled).
          # @!attribute [rw] third_party_integration_partners
          #   @return [::Google::Ads::GoogleAds::V25::Common::CampaignThirdPartyIntegrationPartners]
          #     Third-Party integration partners.
          # @!attribute [rw] ai_max_setting
          #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::AiMaxSetting]
          #     Settings for AI Max in Search and Shopping campaigns.
          # @!attribute [rw] contains_eu_political_advertising
          #   @return [::Google::Ads::GoogleAds::V25::Enums::EuPoliticalAdvertisingStatusEnum::EuPoliticalAdvertisingStatus]
          #     The advertiser should self-declare whether this campaign contains
          #     political advertising content targeted towards the European Union.
          # @!attribute [r] feed_types
          #   @return [::Array<::Google::Ads::GoogleAds::V25::Enums::AssetSetTypeEnum::AssetSetType>]
          #     Output only. Types of feeds that are attached directly to this campaign.
          # @!attribute [rw] view_through_conversion_optimization_enabled
          #   @return [::Boolean]
          #     Whether VTC (View-through Conversion) optimization is enabled for this
          #     campaign. Only allowed for certain Demand Gen and App Campaigns.
          # @!attribute [r] missing_eu_political_advertising_declaration
          #   @return [::Boolean]
          #     Output only. Indicates whether this campaign is missing a declaration about
          #     whether it contains political advertising targeted towards the EU and is
          #     ineligible for any exemptions. If this field is true, use the
          #     contains_eu_political_advertising field to add the required declaration.
          #
          #     This field is read-only.
          # @!attribute [r] aca_migration_date_time
          #   @return [::String]
          #     Output only. The timestamp when the ACA campaign was migrated to AI Max.
          #     The timestamp is in the customer's timezone and in "yyyy-MM-dd HH:mm:ss"
          #     format.
          # @!attribute [r] broad_match_migration_date_time
          #   @return [::String]
          #     Output only. The timestamp when the Broad Match campaign was migrated to AI
          #     Max. The timestamp is in the customer's timezone and in "yyyy-MM-dd
          #     HH:mm:ss" format.
          # @!attribute [rw] bidding_strategy
          #   @return [::String]
          #     The resource name of the portfolio bidding strategy used by the campaign.
          #
          #     Note: The following fields are mutually exclusive: `bidding_strategy`, `commission`, `manual_cpa`, `manual_cpc`, `manual_cpm`, `manual_cpv`, `maximize_conversions`, `maximize_conversion_value`, `target_cpa`, `target_impression_share`, `target_roas`, `target_spend`, `percent_cpc`, `target_cpm`, `fixed_cpm`, `target_cpv`, `target_cpc`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          # @!attribute [rw] commission
          #   @return [::Google::Ads::GoogleAds::V25::Common::Commission]
          #     Commission is an automatic bidding strategy in which the advertiser pays
          #     a certain portion of the conversion value.
          #
          #     Note: The following fields are mutually exclusive: `commission`, `bidding_strategy`, `manual_cpa`, `manual_cpc`, `manual_cpm`, `manual_cpv`, `maximize_conversions`, `maximize_conversion_value`, `target_cpa`, `target_impression_share`, `target_roas`, `target_spend`, `percent_cpc`, `target_cpm`, `fixed_cpm`, `target_cpv`, `target_cpc`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          # @!attribute [rw] manual_cpa
          #   @return [::Google::Ads::GoogleAds::V25::Common::ManualCpa]
          #     Standard Manual CPA bidding strategy.
          #     Manual bidding strategy that allows advertiser to set the bid per
          #     advertiser-specified action. Supported only for Local Services campaigns.
          #
          #     Note: The following fields are mutually exclusive: `manual_cpa`, `bidding_strategy`, `commission`, `manual_cpc`, `manual_cpm`, `manual_cpv`, `maximize_conversions`, `maximize_conversion_value`, `target_cpa`, `target_impression_share`, `target_roas`, `target_spend`, `percent_cpc`, `target_cpm`, `fixed_cpm`, `target_cpv`, `target_cpc`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          # @!attribute [rw] manual_cpc
          #   @return [::Google::Ads::GoogleAds::V25::Common::ManualCpc]
          #     Standard Manual CPC bidding strategy.
          #     Manual click-based bidding where user pays per click.
          #
          #     Note: The following fields are mutually exclusive: `manual_cpc`, `bidding_strategy`, `commission`, `manual_cpa`, `manual_cpm`, `manual_cpv`, `maximize_conversions`, `maximize_conversion_value`, `target_cpa`, `target_impression_share`, `target_roas`, `target_spend`, `percent_cpc`, `target_cpm`, `fixed_cpm`, `target_cpv`, `target_cpc`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          # @!attribute [rw] manual_cpm
          #   @return [::Google::Ads::GoogleAds::V25::Common::ManualCpm]
          #     Standard Manual CPM bidding strategy.
          #     Manual impression-based bidding where user pays per thousand
          #     impressions.
          #
          #     Note: The following fields are mutually exclusive: `manual_cpm`, `bidding_strategy`, `commission`, `manual_cpa`, `manual_cpc`, `manual_cpv`, `maximize_conversions`, `maximize_conversion_value`, `target_cpa`, `target_impression_share`, `target_roas`, `target_spend`, `percent_cpc`, `target_cpm`, `fixed_cpm`, `target_cpv`, `target_cpc`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          # @!attribute [rw] manual_cpv
          #   @return [::Google::Ads::GoogleAds::V25::Common::ManualCpv]
          #     A bidding strategy that pays a configurable amount per video view.
          #
          #     Note: The following fields are mutually exclusive: `manual_cpv`, `bidding_strategy`, `commission`, `manual_cpa`, `manual_cpc`, `manual_cpm`, `maximize_conversions`, `maximize_conversion_value`, `target_cpa`, `target_impression_share`, `target_roas`, `target_spend`, `percent_cpc`, `target_cpm`, `fixed_cpm`, `target_cpv`, `target_cpc`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          # @!attribute [rw] maximize_conversions
          #   @return [::Google::Ads::GoogleAds::V25::Common::MaximizeConversions]
          #     Standard Maximize Conversions bidding strategy that automatically
          #     maximizes number of conversions while spending your budget.
          #
          #     Note: The following fields are mutually exclusive: `maximize_conversions`, `bidding_strategy`, `commission`, `manual_cpa`, `manual_cpc`, `manual_cpm`, `manual_cpv`, `maximize_conversion_value`, `target_cpa`, `target_impression_share`, `target_roas`, `target_spend`, `percent_cpc`, `target_cpm`, `fixed_cpm`, `target_cpv`, `target_cpc`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          # @!attribute [rw] maximize_conversion_value
          #   @return [::Google::Ads::GoogleAds::V25::Common::MaximizeConversionValue]
          #     Standard Maximize Conversion Value bidding strategy that automatically
          #     sets bids to maximize revenue while spending your budget.
          #
          #     Note: The following fields are mutually exclusive: `maximize_conversion_value`, `bidding_strategy`, `commission`, `manual_cpa`, `manual_cpc`, `manual_cpm`, `manual_cpv`, `maximize_conversions`, `target_cpa`, `target_impression_share`, `target_roas`, `target_spend`, `percent_cpc`, `target_cpm`, `fixed_cpm`, `target_cpv`, `target_cpc`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          # @!attribute [rw] target_cpa
          #   @return [::Google::Ads::GoogleAds::V25::Common::TargetCpa]
          #     Standard Target CPA bidding strategy that automatically sets bids to
          #     help get as many conversions as possible at the target
          #     cost-per-acquisition (CPA) you set.
          #
          #     Note: The following fields are mutually exclusive: `target_cpa`, `bidding_strategy`, `commission`, `manual_cpa`, `manual_cpc`, `manual_cpm`, `manual_cpv`, `maximize_conversions`, `maximize_conversion_value`, `target_impression_share`, `target_roas`, `target_spend`, `percent_cpc`, `target_cpm`, `fixed_cpm`, `target_cpv`, `target_cpc`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          # @!attribute [rw] target_impression_share
          #   @return [::Google::Ads::GoogleAds::V25::Common::TargetImpressionShare]
          #     Target Impression Share bidding strategy. An automated bidding strategy
          #     that sets bids to achieve a chosen percentage of impressions.
          #
          #     Note: The following fields are mutually exclusive: `target_impression_share`, `bidding_strategy`, `commission`, `manual_cpa`, `manual_cpc`, `manual_cpm`, `manual_cpv`, `maximize_conversions`, `maximize_conversion_value`, `target_cpa`, `target_roas`, `target_spend`, `percent_cpc`, `target_cpm`, `fixed_cpm`, `target_cpv`, `target_cpc`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          # @!attribute [rw] target_roas
          #   @return [::Google::Ads::GoogleAds::V25::Common::TargetRoas]
          #     Standard Target ROAS bidding strategy that automatically maximizes
          #     revenue while averaging a specific target return on ad spend (ROAS).
          #
          #     Note: The following fields are mutually exclusive: `target_roas`, `bidding_strategy`, `commission`, `manual_cpa`, `manual_cpc`, `manual_cpm`, `manual_cpv`, `maximize_conversions`, `maximize_conversion_value`, `target_cpa`, `target_impression_share`, `target_spend`, `percent_cpc`, `target_cpm`, `fixed_cpm`, `target_cpv`, `target_cpc`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          # @!attribute [rw] target_spend
          #   @return [::Google::Ads::GoogleAds::V25::Common::TargetSpend]
          #     Standard Target Spend bidding strategy that automatically sets your bids
          #     to help get as many clicks as possible within your budget.
          #
          #     Note: The following fields are mutually exclusive: `target_spend`, `bidding_strategy`, `commission`, `manual_cpa`, `manual_cpc`, `manual_cpm`, `manual_cpv`, `maximize_conversions`, `maximize_conversion_value`, `target_cpa`, `target_impression_share`, `target_roas`, `percent_cpc`, `target_cpm`, `fixed_cpm`, `target_cpv`, `target_cpc`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          # @!attribute [rw] percent_cpc
          #   @return [::Google::Ads::GoogleAds::V25::Common::PercentCpc]
          #     Standard Percent Cpc bidding strategy where bids are a fraction of the
          #     advertised price for some good or service.
          #
          #     Note: The following fields are mutually exclusive: `percent_cpc`, `bidding_strategy`, `commission`, `manual_cpa`, `manual_cpc`, `manual_cpm`, `manual_cpv`, `maximize_conversions`, `maximize_conversion_value`, `target_cpa`, `target_impression_share`, `target_roas`, `target_spend`, `target_cpm`, `fixed_cpm`, `target_cpv`, `target_cpc`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          # @!attribute [rw] target_cpm
          #   @return [::Google::Ads::GoogleAds::V25::Common::TargetCpm]
          #     A bidding strategy that automatically optimizes cost per thousand
          #     impressions.
          #
          #     Note: The following fields are mutually exclusive: `target_cpm`, `bidding_strategy`, `commission`, `manual_cpa`, `manual_cpc`, `manual_cpm`, `manual_cpv`, `maximize_conversions`, `maximize_conversion_value`, `target_cpa`, `target_impression_share`, `target_roas`, `target_spend`, `percent_cpc`, `fixed_cpm`, `target_cpv`, `target_cpc`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          # @!attribute [rw] fixed_cpm
          #   @return [::Google::Ads::GoogleAds::V25::Common::FixedCpm]
          #     A manual bidding strategy with a fixed CPM.
          #
          #     Note: The following fields are mutually exclusive: `fixed_cpm`, `bidding_strategy`, `commission`, `manual_cpa`, `manual_cpc`, `manual_cpm`, `manual_cpv`, `maximize_conversions`, `maximize_conversion_value`, `target_cpa`, `target_impression_share`, `target_roas`, `target_spend`, `percent_cpc`, `target_cpm`, `target_cpv`, `target_cpc`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          # @!attribute [rw] target_cpv
          #   @return [::Google::Ads::GoogleAds::V25::Common::TargetCpv]
          #     An automated bidding strategy that sets bids to optimize performance
          #     given the target CPV you set.
          #
          #     Note: The following fields are mutually exclusive: `target_cpv`, `bidding_strategy`, `commission`, `manual_cpa`, `manual_cpc`, `manual_cpm`, `manual_cpv`, `maximize_conversions`, `maximize_conversion_value`, `target_cpa`, `target_impression_share`, `target_roas`, `target_spend`, `percent_cpc`, `target_cpm`, `fixed_cpm`, `target_cpc`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          # @!attribute [rw] target_cpc
          #   @return [::Google::Ads::GoogleAds::V25::Common::TargetCpc]
          #     An automated bidding strategy that sets bids to help get as many clicks
          #     as possible at the target cost-per-click (CPC) you set.
          #
          #     Note: The following fields are mutually exclusive: `target_cpc`, `bidding_strategy`, `commission`, `manual_cpa`, `manual_cpc`, `manual_cpm`, `manual_cpv`, `maximize_conversions`, `maximize_conversion_value`, `target_cpa`, `target_impression_share`, `target_roas`, `target_spend`, `percent_cpc`, `target_cpm`, `fixed_cpm`, `target_cpv`. If a field in that set is populated, all other fields in the set will automatically be cleared.
          class Campaign
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods

            # Information about a campaign being upgraded to Performance Max.
            # @!attribute [r] performance_max_campaign
            #   @return [::String]
            #     Output only. The resource name of the Performance Max campaign the
            #     campaign is upgraded to.
            # @!attribute [r] pre_upgrade_campaign
            #   @return [::String]
            #     Output only. The resource name of the legacy campaign upgraded to
            #     Performance Max.
            # @!attribute [r] status
            #   @return [::Google::Ads::GoogleAds::V25::Enums::PerformanceMaxUpgradeStatusEnum::PerformanceMaxUpgradeStatus]
            #     Output only. The upgrade status of a campaign requested to be upgraded to
            #     Performance Max.
            class PerformanceMaxUpgrade
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # The network settings for the campaign.
            # @!attribute [rw] target_google_search
            #   @return [::Boolean]
            #     Whether ads will be served with google.com search results.
            # @!attribute [rw] target_search_network
            #   @return [::Boolean]
            #     Whether ads will be served on sites in the Google Search Partners Network
            #     (requires `target_google_search` to also be `true`).
            # @!attribute [rw] target_content_network
            #   @return [::Boolean]
            #     Whether ads will be served on specified placements in the Google Display
            #     Network. Placements are specified using the Placement criterion.
            # @!attribute [rw] target_partner_search_network
            #   @return [::Boolean]
            #     Whether ads will be served on the partner network. This is available
            #     only to some select partner accounts. Unless you have been instructed to
            #     use this field, it likely does not apply to your account. This does not
            #     control whether ads will be served on Google Search Partners Network; use
            #     `target_search_network` for that instead.
            # @!attribute [rw] target_youtube
            #   @return [::Boolean]
            #     Whether ads will be served on YouTube.
            # @!attribute [rw] target_google_tv_network
            #   @return [::Boolean]
            #     Whether ads will be served on the Google TV network.
            class NetworkSettings
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Campaign-level settings for hotel ads.
            # @!attribute [rw] hotel_center_id
            #   @return [::Integer]
            #     The linked Hotel Center account.
            # @!attribute [rw] disable_hotel_setting
            #   @return [::Boolean]
            #     Disable the optional hotel setting. This field is currently supported
            #     only for Demand Gen campaigns.
            class HotelSettingInfo
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # The setting for controlling Dynamic Search Ads (DSA).
            # @!attribute [rw] domain_name
            #   @return [::String]
            #     Required. The Internet domain name that this setting represents, for
            #     example, "google.com" or "www.google.com".
            # @!attribute [rw] language_code
            #   @return [::String]
            #     Required. The language code specifying the language of the domain, for
            #     example, "en".
            # @!attribute [rw] use_supplied_urls_only
            #   @return [::Boolean]
            #     Whether the campaign uses advertiser supplied URLs exclusively.
            class DynamicSearchAdsSetting
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # The setting for Shopping campaigns. Defines the universe of products that
            # can be advertised by the campaign, and how this campaign interacts with
            # other Shopping campaigns.
            # @!attribute [rw] merchant_id
            #   @return [::Integer]
            #     ID of the Merchant Center account.
            #     This field is required for create operations. This field is immutable for
            #     Shopping campaigns.
            # @!attribute [rw] feed_label
            #   @return [::String]
            #     Feed label of products to include in the campaign.
            #     Valid feed labels may contain a maximum of 20 characters including
            #     uppercase letters, numbers, hyphens, and underscores.
            #     If you previously used the deprecated `sales_country` in the two-letter
            #     country code (`XX`) format, the `feed_label` field should be used
            #     instead. For more information see the
            #     [feed label](//support.google.com/merchants/answer/12453549)
            #     support article.
            # @!attribute [rw] campaign_priority
            #   @return [::Integer]
            #     Priority of the campaign. Campaigns with numerically higher priorities
            #     take precedence over those with lower priorities.
            #     This field is required for Shopping campaigns, with values between 0 and
            #     2, inclusive.
            #     This field is optional for Smart Shopping campaigns, but must be equal to
            #     3 if set.
            # @!attribute [rw] enable_local
            #   @return [::Boolean]
            #     Whether to include local products.
            # @!attribute [rw] use_vehicle_inventory
            #   @return [::Boolean]
            #     Immutable. Whether to target Vehicle Listing inventory. This field is
            #     supported only in Smart Shopping Campaigns. For setting Vehicle Listing
            #     inventory in Performance Max campaigns, use `listing_type` instead.
            # @!attribute [rw] advertising_partner_ids
            #   @return [::Array<::Integer>]
            #     The list of Google Ads accounts IDs of advertising partners cooperating
            #     within the campaign.
            #     This feature is currently available only for accounts having an
            #     advertising partner link. Once set, the field is immutable.
            #     This feature is currently supported only for Performance Max, Shopping,
            #     Search and Demand Gen campaign types.
            # @!attribute [rw] disable_product_feed
            #   @return [::Boolean]
            #     Disable the optional product feed. This field is currently supported
            #     only for Demand Gen campaigns. See
            #     https://support.google.com/google-ads/answer/13721750 to learn more about
            #     this feature.
            # @!attribute [rw] ignore_brand_exclusion_in_shopping_ads
            #   @return [::Boolean]
            #     If true, brand exclusions are ignored for Shopping ads.
            #     Only supported for Shopping campaigns.
            class ShoppingSetting
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Campaign-level settings for tracking information.
            # @!attribute [r] tracking_url
            #   @return [::String]
            #     Output only. The url used for dynamic tracking.
            class TrackingSetting
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Represents a collection of settings related to ads geotargeting.
            # @!attribute [rw] positive_geo_target_type
            #   @return [::Google::Ads::GoogleAds::V25::Enums::PositiveGeoTargetTypeEnum::PositiveGeoTargetType]
            #     The setting used for positive geotargeting in this particular campaign.
            # @!attribute [rw] negative_geo_target_type
            #   @return [::Google::Ads::GoogleAds::V25::Enums::NegativeGeoTargetTypeEnum::NegativeGeoTargetType]
            #     The setting used for negative geotargeting in this particular campaign.
            class GeoTargetTypeSetting
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Campaign setting for local campaigns.
            # @!attribute [rw] location_source_type
            #   @return [::Google::Ads::GoogleAds::V25::Enums::LocationSourceTypeEnum::LocationSourceType]
            #     The location source type for this local campaign.
            class LocalCampaignSetting
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Campaign-level settings for App Campaigns.
            # @!attribute [rw] bidding_strategy_goal_type
            #   @return [::Google::Ads::GoogleAds::V25::Enums::AppCampaignBiddingStrategyGoalTypeEnum::AppCampaignBiddingStrategyGoalType]
            #     Represents the goal which the bidding strategy of this app campaign
            #     should optimize towards.
            # @!attribute [rw] app_id
            #   @return [::String]
            #     Immutable. A string that uniquely identifies a mobile application.
            # @!attribute [rw] app_store
            #   @return [::Google::Ads::GoogleAds::V25::Enums::AppCampaignAppStoreEnum::AppCampaignAppStore]
            #     Immutable. The application store that distributes this specific app.
            class AppCampaignSetting
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Describes how unbranded pharma ads will be displayed.
            # @!attribute [rw] vanity_pharma_display_url_mode
            #   @return [::Google::Ads::GoogleAds::V25::Enums::VanityPharmaDisplayUrlModeEnum::VanityPharmaDisplayUrlMode]
            #     The display mode for vanity pharma URLs.
            # @!attribute [rw] vanity_pharma_text
            #   @return [::Google::Ads::GoogleAds::V25::Enums::VanityPharmaTextEnum::VanityPharmaText]
            #     The text that will be displayed in display URL of the text ad when
            #     website description is the selected display mode for vanity pharma URLs.
            class VanityPharma
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Selective optimization setting for this campaign, which includes a set of
            # conversion actions to optimize this campaign towards.
            # This feature only applies to app campaigns that use MULTI_CHANNEL as
            # AdvertisingChannelType and APP_CAMPAIGN or APP_CAMPAIGN_FOR_ENGAGEMENT as
            # AdvertisingChannelSubType.
            # @!attribute [rw] conversion_actions
            #   @return [::Array<::String>]
            #     The selected set of resource names for conversion actions for optimizing
            #     this campaign.
            class SelectiveOptimization
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Optimization goal setting for this campaign, which includes a set of
            # optimization goal types.
            # @!attribute [rw] optimization_goal_types
            #   @return [::Array<::Google::Ads::GoogleAds::V25::Enums::OptimizationGoalTypeEnum::OptimizationGoalType>]
            #     The list of optimization goal types.
            class OptimizationGoalSetting
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Settings for the audience targeting.
            # @!attribute [rw] use_audience_grouped
            #   @return [::Boolean]
            #     Immutable. If true, this campaign uses an Audience resource for audience
            #     targeting. If false, this campaign may use audience segment criteria
            #     instead.
            class AudienceSetting
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Settings for LocalServicesCampaign subresource.
            # @!attribute [rw] category_bids
            #   @return [::Array<::Google::Ads::GoogleAds::V25::Resources::Campaign::CategoryBid>]
            #     Categorical level bids associated with MANUAL_CPA bidding strategy.
            class LocalServicesCampaignSettings
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Settings for Local Services Performance Max Campaign subresource.
            # @!attribute [rw] navigational_query_leads_enabled
            #   @return [::Boolean]
            #     Whether to use navigational query filter.
            # @!attribute [rw] founding_year
            #   @return [::Integer]
            #     Founding year of the business.
            # @!attribute [rw] country_code
            #   @return [::String]
            #     Immutable. Country code of the Local Services Ad. Set once during Ad
            #     Creation and used to determine verification requirements and validate
            #     location criterion selection; upper-case, two-letter codes as defined by
            #     ISO-3166.
            # @!attribute [rw] phone_numbers
            #   @return [::Array<::Google::Ads::GoogleAds::V25::Common::LocalServicesPhoneNumber>]
            #     List of phone numbers associated with the provider.
            class LocalServicesPmaxCampaignSettings
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Category bids in LocalServicesReportingCampaignSettings.
            # @!attribute [rw] category_id
            #   @return [::String]
            #     Category for which the bid will be associated with. For example,
            #     xcat:service_area_business_plumber.
            # @!attribute [rw] manual_cpa_bid_micros
            #   @return [::Integer]
            #     Manual CPA bid for the category. Bid must be greater than the
            #     reserve price associated for that category. Value is in micros
            #     and in the advertiser's currency.
            # @!attribute [rw] target_cpa_bid_micros
            #   @return [::Integer]
            #     Target CPA bid for the category. Value is in micros and in the
            #     advertiser's currency.
            class CategoryBid
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Settings for Travel campaign.
            # @!attribute [rw] travel_account_id
            #   @return [::Integer]
            #     Immutable. The Travel account ID associated with the Travel campaign.
            class TravelCampaignSettings
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Settings for Demand Gen campaign.
            # @!attribute [rw] upgraded_targeting
            #   @return [::Boolean]
            #     Immutable. Specifies whether this campaign uses upgraded targeting
            #     options. When this field is set to `true`, you can use location and
            #     language targeting at the ad group level as opposed to the standard
            #     campaign-level targeting. This field defaults to `true`, and can only be
            #     set when creating a campaign.
            class DemandGenCampaignSettings
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Settings for Video campaign.
            # @!attribute [rw] video_ad_sequence
            #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::VideoCampaignSettings::VideoAdSequence]
            #     Container for video ads sequencing definition.
            # @!attribute [rw] reservation_ad_category_self_disclosure
            #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::VideoCampaignSettings::ReservationAdCategorySelfDisclosure]
            #     Ad category self-disclosure for campaigns with the FIXED_CPM or
            #     FIXED_SHARE_OF_VOICE bidding strategies.
            # @!attribute [r] booking_details
            #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::VideoCampaignSettings::BookingDetails]
            #     Output only. Booking information for campaigns with the FIXED_CPM or
            #     FIXED_SHARE_OF_VOICE bidding strategies.
            # @!attribute [rw] video_ad_inventory_control
            #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::VideoCampaignSettings::VideoAdInventoryControl]
            #     Inventory control for video responsive ads in reach campaigns.
            #
            #     Note: The following fields are mutually exclusive: `video_ad_inventory_control`, `video_ad_format_control`. If a field in that set is populated, all other fields in the set will automatically be cleared.
            # @!attribute [rw] video_ad_format_control
            #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::VideoCampaignSettings::VideoAdFormatControl]
            #     Format-restricting control enabling usage of video responsive ads in
            #     format defined Video campaigns (for example, non-skippable).
            #
            #     Note: The following fields are mutually exclusive: `video_ad_format_control`, `video_ad_inventory_control`. If a field in that set is populated, all other fields in the set will automatically be cleared.
            class VideoCampaignSettings
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods

              # For campaigns using video responsive ads inventory controls determine on
              # which inventories the ads can be shown. This only applies for campaigns
              # with the bidding strategies TARGET_CPM and FIXED_CPM.
              # @!attribute [rw] allow_in_stream
              #   @return [::Boolean]
              #     Determine if video responsive ads can be used for in-stream video ads.
              # @!attribute [rw] allow_in_feed
              #   @return [::Boolean]
              #     Determine if video responsive ads can be used for in-feed video ads.
              # @!attribute [rw] allow_shorts
              #   @return [::Boolean]
              #     Determine if video responsive ads can be used as shorts format.
              # @!attribute [rw] allow_non_skippable_in_stream
              #   @return [::Boolean]
              #     Determine if video responsive ads can be used for non-skippable
              #     in-stream ads. This is only available for campaigns that allow mixing
              #     of non-skippable with other formats (Video reach campaign with Target
              #     Frequency bidding strategy goal).
              class VideoAdInventoryControl
                include ::Google::Protobuf::MessageExts
                extend ::Google::Protobuf::MessageExts::ClassMethods
              end

              # Format-restricting control enabling usage of video responsive ads in
              # format defined Video campaigns (for example, non-skippable).
              # @!attribute [rw] format_restriction
              #   @return [::Google::Ads::GoogleAds::V25::Enums::VideoAdFormatRestrictionEnum::VideoAdFormatRestriction]
              #     All contained responsive ads are expected to respect this restriction.
              # @!attribute [rw] non_skippable_in_stream_restrictions
              #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::VideoCampaignSettings::NonSkippableInStreamRestrictions]
              #     Restrictions for non-skippable format.
              class VideoAdFormatControl
                include ::Google::Protobuf::MessageExts
                extend ::Google::Protobuf::MessageExts::ClassMethods
              end

              # Restrictions for non-skippable format.
              # @!attribute [rw] min_duration
              #   @return [::Google::Ads::GoogleAds::V25::Enums::NonSkippableMinDurationEnum::NonSkippableMinDuration]
              #     The minimum allowed duration for non-skippable ads.
              # @!attribute [rw] max_duration
              #   @return [::Google::Ads::GoogleAds::V25::Enums::NonSkippableMaxDurationEnum::NonSkippableMaxDuration]
              #     The maximum allowed duration for non-skippable ads.
              class NonSkippableInStreamRestrictions
                include ::Google::Protobuf::MessageExts
                extend ::Google::Protobuf::MessageExts::ClassMethods
              end

              # Container for video ads sequencing definition.
              # @!attribute [rw] steps
              #   @return [::Array<::Google::Ads::GoogleAds::V25::Resources::Campaign::VideoCampaignSettings::VideoAdSequenceStep>]
              #     The list of sequence steps and data associated with them.
              # @!attribute [rw] minimum_duration
              #   @return [::Google::Ads::GoogleAds::V25::Enums::VideoAdSequenceMinimumDurationEnum::VideoAdSequenceMinimumDuration]
              #     Users are eligible to repeat sequence after this period. Defaults to
              #     WEEK if not specified.
              class VideoAdSequence
                include ::Google::Protobuf::MessageExts
                extend ::Google::Protobuf::MessageExts::ClassMethods
              end

              # Information about a step within a video sequence.
              # @!attribute [rw] video_ad_sequence_step_id
              #   @return [::Integer]
              #     The ID of this sequence step.
              # @!attribute [rw] asset_id
              #   @return [::Integer]
              #     The ID of the Asset for this step. The asset must be type
              #     YOUTUBE_VIDEO.
              # @!attribute [rw] ad_group_type
              #   @return [::Google::Ads::GoogleAds::V25::Enums::AdGroupTypeEnum::AdGroupType]
              #     The ad group type for this step (denoting the video format).
              # @!attribute [rw] previous_step_id
              #   @return [::Integer]
              #     The ID of the previous step. This field is required for all
              #     steps except the first one. It must point to a step that appears in the
              #     step definition list before this step.
              # @!attribute [rw] previous_step_interaction_type
              #   @return [::Google::Ads::GoogleAds::V25::Enums::VideoAdSequenceInteractionTypeEnum::VideoAdSequenceInteractionType]
              #     Type of interaction *on the previous step* required in order for the
              #     user to advance to this step. As with the previous step ID, it's
              #     required for every step except for the first one.
              class VideoAdSequenceStep
                include ::Google::Protobuf::MessageExts
                extend ::Google::Protobuf::MessageExts::ClassMethods
              end

              # Container for ad category self-disclosure for campaigns with the
              # FIXED_CPM or FIXED_SHARE_OF_VOICE bidding strategies.
              # @!attribute [rw] gambling
              #   @return [::Boolean]
              #     The campaign is expected to contain gambling-related ads.
              # @!attribute [rw] alcohol
              #   @return [::Boolean]
              #     The campaign is expected to contain alcohol-related ads.
              # @!attribute [rw] politics
              #   @return [::Boolean]
              #     The campaign is expected to contain politics-related ads.
              class ReservationAdCategorySelfDisclosure
                include ::Google::Protobuf::MessageExts
                extend ::Google::Protobuf::MessageExts::ClassMethods
              end

              # Container for booking details for campaigns with the FIXED_CPM or
              # FIXED_SHARE_OF_VOICE bidding strategies.
              # @!attribute [r] status
              #   @return [::Google::Ads::GoogleAds::V25::Enums::BookingStatusEnum::BookingStatus]
              #     Output only. The status of the booking.
              # @!attribute [r] hold_expiration_date_time
              #   @return [::String]
              #     Output only. Time until which booked inventory will be held or has been
              #     held for this campaign. Available for status HELD and HOLD_EXPIRED.
              #     Format is "yyyy-MM-dd HH:mm:ss" in the customer's time zone.
              # @!attribute [r] cancellation_date_time
              #   @return [::String]
              #     Output only. Time when the booked inventory of this campaign will be
              #     cancelled or has been cancelled. Available for primary status
              #     NOT_ELIGIBLE if the campaign will be cancelled and for primary status
              #     reason BOOKING_CANCELLED. Format is "yyyy-MM-dd HH:mm:ss" in the
              #     customer's time zone.
              class BookingDetails
                include ::Google::Protobuf::MessageExts
                extend ::Google::Protobuf::MessageExts::ClassMethods
              end
            end

            # Settings for Performance Max campaigns.
            # @!attribute [rw] brand_targeting_overrides
            #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::PmaxCampaignSettings::BrandTargetingOverrides]
            #     Overrides of brand targeting for various ad types.
            # @!attribute [rw] local_services_pmax_campaign_settings
            #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::LocalServicesPmaxCampaignSettings]
            #     The Local Services Campaign related settings. Only updates are available
            #     for existing Local Services Pmax campaigns.
            # @!attribute [r] local_services_enabled
            #   @return [::Boolean]
            #     Output only. Indicates whether the Performance Max campaign is a Local
            #     Services campaign.
            class PmaxCampaignSettings
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods

              # Overrides of brand targeting for various ad types.
              # @!attribute [rw] ignore_exclusions_for_shopping_ads
              #   @return [::Boolean]
              #     If true, brand exclusions are ignored for Shopping ads.
              class BrandTargetingOverrides
                include ::Google::Protobuf::MessageExts
                extend ::Google::Protobuf::MessageExts::ClassMethods
              end
            end

            # Asset automation setting contains pair of AssetAutomationType and the
            # asset automation opt-in/out status
            # @!attribute [rw] asset_automation_type
            #   @return [::Google::Ads::GoogleAds::V25::Enums::AssetAutomationTypeEnum::AssetAutomationType]
            #     The asset automation type advertiser would like to opt-in/out.
            # @!attribute [rw] asset_automation_status
            #   @return [::Google::Ads::GoogleAds::V25::Enums::AssetAutomationStatusEnum::AssetAutomationStatus]
            #     The opt-in/out status of asset automation type.
            class AssetAutomationSetting
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Settings that control the visual appearance of your brand in a campaign's
            # automatically generated assets and formats. Only applicable to Performance
            # Max campaigns.
            # @!attribute [rw] main_color
            #   @return [::String]
            #     The main brand color, entered as a hex code (e.g., #00ff00). You must
            #     provide the main_color if you provide an accent_color.
            # @!attribute [rw] accent_color
            #   @return [::String]
            #     The accent brand color, entered as a hex code (e.g., #00ff00). You must
            #     provide the accent_color if you provide a main_color.
            # @!attribute [rw] predefined_font_family
            #   @return [::String]
            #     The brand's font family. Must be one of the following Google Fonts (case
            #     sensitive): Open Sans, Roboto, Montserrat, Poppins, Lato, Oswald,
            #     Playfair Display, Roboto Slab.
            class BrandGuidelines
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Settings to control automatically generated text assets.
            # @!attribute [rw] term_exclusions
            #   @return [::Array<::String>]
            #     Exact words or phrases that will be excluded from generated text
            #     assets. At most 25 exclusions may be provided. Valid exclusions may
            #     contain a maximum of 30 characters.
            # @!attribute [rw] messaging_restrictions
            #   @return [::Array<::Google::Ads::GoogleAds::V25::Resources::Campaign::MessagingRestriction>]
            #     Freeform instructions that will be used to guide text asset generation
            #     using LLM inference. At most 40 restrictions may be provided.
            class TextGuidelines
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Freeform instructions that will be used to guide text asset generation
            # using LLM inference.
            # @!attribute [rw] restriction_text
            #   @return [::String]
            #     Freeform instructions to guide text asset generation using LLM
            #     inference. Valid instructions may contain a maximum of 300 characters.
            # @!attribute [rw] restriction_type
            #   @return [::Google::Ads::GoogleAds::V25::Enums::MessagingRestrictionTypeEnum::MessagingRestrictionType]
            #     Determines how the guideline is applied. Only
            #     `RESTRICTION_BASED_EXCLUSION` is currently supported.
            class MessagingRestriction
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end

            # Settings for AI Max in Search and Shopping campaigns.
            # @!attribute [rw] enable_ai_max
            #   @return [::Boolean]
            #     Controls whether or not AI Max features are served for this campaign.
            #
            #     Individual AI Max features are enabled or disabled by their respective
            #     settings. But if enable_ai_max is set to false or cleared, then no AI
            #     Max features will serve for this campaign, regardless of the other
            #     settings.
            #
            #     Supported in Search and Shopping campaigns.
            #
            #     For Search campaigns, Search Term Matching is enabled by default when
            #     AI Max is enabled, and can be disabled at the ad group level.
            #
            #     For Shopping campaigns, Text customization is always enabled when AI Max
            #     is enabled.
            # @!attribute [r] bundling_required
            #   @return [::Google::Ads::GoogleAds::V25::Resources::Campaign::AiMaxSetting::AiMaxBundlingRequired]
            #     Output only. Search campaigns only. Indicates whether a campaign has
            #     adopted AI Max before, and is required to have AI Max enabled to adopt
            #     campaign-level text asset automation and brand list targeting in all API
            #     versions.
            class AiMaxSetting
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods

              # Enum describing whether AI Max must be enabled to serve and update
              # text asset automation and brand list features newly bundled with AI Max.
              module AiMaxBundlingRequired
                # Not specified.
                UNSPECIFIED = 0

                # Used for return value only. Represents value unknown in this version.
                UNKNOWN = 1

                # Search campaign is using text asset automation or brand
                # list targeting, and AI Max is not required to be enabled to serve these
                # features.
                NOT_REQUIRED = 2

                # AI Max is required to be enabled for this search campaign to serve
                # existing text asset automation and brand list targeting, or to add new
                # text asset automation and brand list targeting settings.
                REQUIRED = 3
              end
            end
          end
        end
      end
    end
  end
end
