# frozen_string_literal: true

# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "bundler/gem_tasks"
require "rubocop/rake_task"
require "rake/testtask"

RuboCop::RakeTask.new # Configuration is in .rubocop.yml
Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

Rake::Task[:build].enhance [:compile_protos]
Rake::Task[:clean].enhance [:clean_protos]

desc "Run the CI build"
task :ci do
  puts "\nBUILDING gapic-showcase-test\n"
  puts "\ngapic-showcase-test rubocop\n"
  Rake::Task[:rubocop].invoke
  puts "\ngapic-showcase-test compile_protos\n"
  Rake::Task[:compile_protos].invoke
  puts "\ngapic-showcase-test test\n"
  Rake::Task[:test].invoke
end

desc "Install gapic-generator and protoc plugins"
task :bundle_gapic_generator do
  Bundler.with_clean_env do
    sh 'cd .. && bundle install'
  end
end

desc "Compile showcase protos"
task :compile_protos do
  Rake::Task[:clean_protos].invoke
  Rake::Task[:bundle_gapic_generator].invoke

  command = []
  command << "grpc_tools_ruby_protoc"
  command << "--ruby_gapic_out=lib"
  command << "-I./showcase-protos"
  command << "./showcase-protos/google/showcase/v1alpha3/echo.proto"

  sh *command
end

desc "Remove the compiled protos."
task :clean_protos do
  Dir.glob('lib/**/*').select{ |file| /.*_pb\.rb/.match file }
                      .each { |file| File.delete  file }
end

task :default => :ci
