---
:transports: ["rest"]
:gem:
  :name: google-cloud-compute
  :description: google-cloud-compute is the official client library for the Google Cloud Compute API.
  :summary: Google Cloud Compute API.
  :version_dependencies: v1:0.0
  :extra_dependencies:
    gapic-common: ">= 0.6|< 2.a"
    google-cloud-common: "~>1.0"
:generate_metadata: false
