---
:gem:
  :name: "google-cloud-document_ai-v1beta3"
:defaults:
  :service:
    :default_host: "documentai.googleapis.com"
    :oauth_scopes:
      - https://www.googleapis.com/auth/cloud-platform
:generate_metadata: false
