---
:gem:
  :name: "google-cloud-language-v1"
  :api_shortname: language
:defaults:
  :service:
    :default_host: "language.googleapis.com"
    :oauth_scopes:
      - https://www.googleapis.com/auth/cloud-platform
:transports: ["grpc", "rest"]
