---
:gem:
  :name: google-cloud-secret_manager
  :title: Secret Manager
  :summary: Stores, manages, and secures access to application secrets.
  :env_prefix: SECRET_MANAGER
  :version_dependencies: v1beta1:0.2;v1:1.0
  :migration_version: "1.0"
  :product_documentation_url: https://cloud.google.com/secret-manager/docs
  :api_id: secretmanager
