---
:gem:
  :name: google-cloud-secret_manager-v1beta1
  :title: Secret Manager V1beta1
  :summary: Stores, manages, and secures access to application secrets.
  :env_prefix: SECRET_MANAGER
:defaults:
  :service:
    :default_host: secretmanager.googleapis.com
    :oauth_scopes:
      - https://www.googleapis.com/auth/cloud-platform
