# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!

require "helper"
require "gapic/rest"
require "google/cloud/location/locations_pb"
require "google/cloud/location/locations/rest"


class ::Google::Cloud::Location::Locations::Rest::ClientTest < Minitest::Test
  class ClientStub
    attr_accessor :call_count, :requests

    def initialize response, &block
      @response = response
      @block = block
      @call_count = 0
      @requests = []
    end

    def make_get_request uri:, params: {}, options: {}
      make_http_request :get, uri: uri, body: nil, params: params, options: options
    end

    def make_delete_request uri:, params: {}, options: {}
      make_http_request :delete, uri: uri, body: nil, params: params, options: options
    end

    def make_post_request uri:, body: nil, params: {}, options: {}
      make_http_request :post, uri: uri, body: body, params: params, options: options
    end

    def make_patch_request uri:, body:, params: {}, options: {}
      make_http_request :patch, uri: uri, body: body, params: params, options: options
    end

    def make_put_request uri:, body:, params: {}, options: {}
      make_http_request :put, uri: uri, body: body, params: params, options: options
    end

    def make_http_request *args, **kwargs
      @call_count += 1

      @requests << @block&.call(*args, **kwargs)

      @response
    end
  end

  def test_list_locations
    # Create test objects.
    client_result = ::Google::Cloud::Location::ListLocationsResponse.new
    http_response = OpenStruct.new body: client_result.to_json

    call_options = {}

    # Create request parameters for a unary method.
    name = "hello world"
    filter = "hello world"
    page_size = 42
    page_token = "hello world"

    list_locations_client_stub = ClientStub.new http_response do |_verb, uri:, body:, params:, options:|
      assert options.metadata.key? :"x-goog-api-client"
      assert options.metadata[:"x-goog-api-client"].include? "rest"
      refute options.metadata[:"x-goog-api-client"].include? "grpc"
    end

    ::Google::Cloud::Location::Locations::Rest::ServiceStub.stub :transcode_list_locations_request, ["", "", {}] do
      Gapic::Rest::ClientStub.stub :new, list_locations_client_stub do
        # Create client
        client = ::Google::Cloud::Location::Locations::Rest::Client.new do |config|
          config.credentials = :dummy_value
        end

        # Use hash object
        client.list_locations({ name: name, filter: filter, page_size: page_size,
page_token: page_token }) do |_result, response|
          assert_equal http_response, response
        end

        # Use named arguments
        client.list_locations name: name, filter: filter, page_size: page_size,
                              page_token: page_token do |_result, response|
          assert_equal http_response, response
        end

        # Use protobuf object
        client.list_locations ::Google::Cloud::Location::ListLocationsRequest.new(name: name, filter: filter,
                                                                                  page_size: page_size, page_token: page_token) do |_result, response|
          assert_equal http_response, response
        end

        # Use hash object with options
        client.list_locations({ name: name, filter: filter, page_size: page_size, page_token: page_token },
                              call_options) do |_result, response|
          assert_equal http_response, response
        end

        # Use protobuf object with options
        client.list_locations(
          ::Google::Cloud::Location::ListLocationsRequest.new(name: name, filter: filter, page_size: page_size,
                                                              page_token: page_token), call_options
        ) do |_result, response|
          assert_equal http_response, response
        end

        # Verify method calls
        assert_equal 5, list_locations_client_stub.call_count
      end
    end
  end

  def test_get_location
    # Create test objects.
    client_result = ::Google::Cloud::Location::Location.new
    http_response = OpenStruct.new body: client_result.to_json

    call_options = {}

    # Create request parameters for a unary method.
    name = "hello world"

    get_location_client_stub = ClientStub.new http_response do |_verb, uri:, body:, params:, options:|
      assert options.metadata.key? :"x-goog-api-client"
      assert options.metadata[:"x-goog-api-client"].include? "rest"
      refute options.metadata[:"x-goog-api-client"].include? "grpc"
    end

    ::Google::Cloud::Location::Locations::Rest::ServiceStub.stub :transcode_get_location_request, ["", "", {}] do
      Gapic::Rest::ClientStub.stub :new, get_location_client_stub do
        # Create client
        client = ::Google::Cloud::Location::Locations::Rest::Client.new do |config|
          config.credentials = :dummy_value
        end

        # Use hash object
        client.get_location({ name: name }) do |_result, response|
          assert_equal http_response, response
        end

        # Use named arguments
        client.get_location name: name do |_result, response|
          assert_equal http_response, response
        end

        # Use protobuf object
        client.get_location ::Google::Cloud::Location::GetLocationRequest.new(name: name) do |_result, response|
          assert_equal http_response, response
        end

        # Use hash object with options
        client.get_location({ name: name }, call_options) do |_result, response|
          assert_equal http_response, response
        end

        # Use protobuf object with options
        client.get_location(::Google::Cloud::Location::GetLocationRequest.new(name: name),
                            call_options) do |_result, response|
          assert_equal http_response, response
        end

        # Verify method calls
        assert_equal 5, get_location_client_stub.call_count
      end
    end
  end

  def test_configure
    credentials_token = :dummy_value

    client = block_config = config = nil
    Gapic::Rest::ClientStub.stub :new, nil do
      client = ::Google::Cloud::Location::Locations::Rest::Client.new do |config|
        config.credentials = credentials_token
      end
    end

    config = client.configure do |c|
      block_config = c
    end

    assert_same block_config, config
    assert_kind_of ::Google::Cloud::Location::Locations::Rest::Client::Configuration, config
  end
end
