inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "test/**/*"

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 15

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/gapic-common.rb"

Style/Documentation:
  Exclude:
    - "lib/gapic/grpc/service_stub/rpc_call.rb"
    - "lib/gapic/grpc/status_details.rb"

Style/CaseEquality:
  Exclude:
    - "lib/gapic/config.rb"
