inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "test/**/*"

Metrics/ClassLength:
  Exclude:
    - "lib/gapic/generic_lro/operation.rb"
    - "lib/gapic/rest/grpc_transcoder.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/gapic/headers.rb"
    - "lib/gapic/rest/client_stub.rb"

Metrics/PerceivedComplexity:
  Exclude:
    - "lib/gapic/headers.rb"
    - "lib/gapic/rest/client_stub.rb"

Naming/FileName:
  Exclude:
    - "lib/gapic-common.rb"

Style/Documentation:
  Exclude:
    - "lib/gapic/grpc/service_stub/rpc_call.rb"
    - "lib/gapic/grpc/status_details.rb"

Style/CaseEquality:
  Exclude:
    - "lib/gapic/config.rb"
