inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "gapic-common.gemspec"
    - "test/**/*"

Metrics/AbcSize:
  Exclude:
    - "lib/gapic/config.rb"
Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/gapic/config.rb"
Metrics/MethodLength:
  Exclude:
    - "lib/gapic/config.rb"
Metrics/PerceivedComplexity:
  Exclude:
    - "lib/gapic/config.rb"
    - "lib/gapic/grpc/stub.rb"

Naming/FileName:
  Exclude:
    - "lib/gapic-common.rb"

Style/Documentation:
  Exclude:
    - "lib/gapic/api_call.rb"
    - "lib/gapic/errors.rb"
    - "lib/gapic/grpc/status_details.rb"
Style/GuardClause:
  Exclude:
    - "lib/gapic/grpc/stub.rb"
Style/CaseEquality:
  Exclude:
    - "lib/gapic/config.rb"
