source "https://rubygems.org"

# Specify your gem's dependencies in gapic-common.gemspec
gemspec

gem "concurrent-ruby", "~> 1.2.2"
gem "google-cloud-core", "~> 1.5"
gem "google-style", ">= 1.27.0", "< 1.30.1"
gem "grpc-tools", "~> 1.60.0"
gem "minitest", "~> 5.16"
gem "minitest-autotest", "~> 1.0"
gem "minitest-focus", "~> 1.1"
gem "minitest-rg", "~> 5.2"
gem "pry", ">= 0.14"
gem "redcarpet", "~> 3.0"
gem "yard", "~> 0.9"
