source "https://rubygems.org"

gemspec

gem "concurrent-ruby", "~> 1.3"
gem "googleapis-common-protos-types", "~> 1.15"
gem "google-cloud-core", "~> 1.7"
gem "google-style", "~> 1.30.0"
gem "grpc-tools", "~> 1.65"
gem "minitest", "~> 5.24"
gem "minitest-autotest", "~> 1.0"
gem "minitest-focus", "~> 1.4"
gem "minitest-rg", "~> 5.3"
gem "pry", ">= 0.14"
gem "redcarpet", "~> 3.0"
gem "yard", "~> 0.9"
