# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: google/cloud/compute/v1/compute_small.proto for package 'Google.Cloud.Compute.V1'
# Original file comments:
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the disco-to-proto3-converter. DO NOT EDIT!
# Source Discovery file: compute.v1.small.json
# Source file revision: 20200302
# API name: compute
# API version: v1
#

require 'grpc'
require 'google/cloud/compute/v1/compute_small_pb'

module Google
  module Cloud
    module Compute
      module V1
        module Addresses
          #
          # Services
          #
          # The Addresses API.
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'google.cloud.compute.v1.Addresses'

            # Retrieves an aggregated list of addresses.
            rpc :AggregatedList, Google::Cloud::Compute::V1::AggregatedListAddressesRequest, Google::Cloud::Compute::V1::AddressAggregatedList
            # Deletes the specified address resource.
            rpc :Delete, Google::Cloud::Compute::V1::DeleteAddressRequest, Google::Cloud::Compute::V1::Operation
            # Creates an address resource in the specified project by using the data included in the request.
            rpc :Insert, Google::Cloud::Compute::V1::InsertAddressRequest, Google::Cloud::Compute::V1::Operation
            # Retrieves a list of addresses contained within the specified region.
            rpc :List, Google::Cloud::Compute::V1::ListAddressesRequest, Google::Cloud::Compute::V1::AddressList
          end

          Stub = Service.rpc_stub_class
        end
        module RegionOperations
          # The RegionOperations API.
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'google.cloud.compute.v1.RegionOperations'

            # Retrieves the specified region-specific Operations resource.
            rpc :Get, Google::Cloud::Compute::V1::GetRegionOperationRequest, Google::Cloud::Compute::V1::Operation
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
