# frozen_string_literal: true

gem "gapic-generator", path: "../gapic-generator"
gem "gapic-generator-cloud", path: "../gapic-generator-cloud"
gem "google-gax"
gem "rake", "~> 10.0"
gem "grpc-tools", "~> 1.18"
