# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: testing/nonstandard_lro_grpc/nonstandard_lro_grpc.proto for package 'Testing.NonstandardLroGrpc'

require 'grpc'
require 'testing/nonstandard_lro_grpc/nonstandard_lro_grpc_pb'

module Testing
  module NonstandardLroGrpc
    module PlainLroConsumer
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'testing.nonstandardlrogrpc.PlainLroConsumer'

        rpc :PlainLroRpc, ::Testing::NonstandardLroGrpc::Request, ::Testing::NonstandardLroGrpc::NonstandardOperation
      end

      Stub = Service.rpc_stub_class
    end
    module PlainLroProvider
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'testing.nonstandardlrogrpc.PlainLroProvider'

        rpc :Get, ::Testing::NonstandardLroGrpc::LroGetRequest, ::Testing::NonstandardLroGrpc::NonstandardOperation
      end

      Stub = Service.rpc_stub_class
    end
    module AnotherLroProvider
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'testing.nonstandardlrogrpc.AnotherLroProvider'

        rpc :GetAnother, ::Testing::NonstandardLroGrpc::LroAnotherGetRequest, ::Testing::NonstandardLroGrpc::NonstandardOperation
      end

      Stub = Service.rpc_stub_class
    end
    module AllSubclientsConsumer
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'testing.nonstandardlrogrpc.AllSubclientsConsumer'

        rpc :PlainLroRpc, ::Testing::NonstandardLroGrpc::Request, ::Testing::NonstandardLroGrpc::NonstandardOperation
        rpc :AnotherLroRpc, ::Testing::NonstandardLroGrpc::AnotherRequest, ::Testing::NonstandardLroGrpc::NonstandardOperation
        rpc :NonCopyAnotherLroRpc, ::Testing::NonstandardLroGrpc::NonCopyRequest, ::Testing::NonstandardLroGrpc::NonstandardOperation
        rpc :AipLRO, ::Testing::NonstandardLroGrpc::Request, ::Google::Longrunning::Operation
      end

      Stub = Service.rpc_stub_class
    end
  end
end
