inherit_gem:
  google-style: google-style.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - expected_output/**/*

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInMultilineCall: true
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
