# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in gapic-generator-ads.gemspec
gemspec

gem "gapic-generator", path: "../gapic-generator"

gem "grpc-tools", ">= 1.60.0", "< 1.78.2"
gem "minitest", "~> 5.16"
gem "minitest-autotest", "~> 1.0"
gem "minitest-focus", "~> 1.0"
gem "pry", ">= 0.14"
gem "redcarpet", "~> 3.0"
gem "yard", "~> 0.9"
