# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in gapic-generator-ads.gemspec
gemspec

gem "gapic-generator", path: "../gapic-generator"
