# frozen_string_literal: true

source "https://rubygems.org"

gem "gapic-generator",       path: "../../gapic-generator"
gem "gapic-generator-ads", path: "../../gapic-generator-ads"
gem "gapic-generator-cloud", path: "../../gapic-generator-cloud"
gem "grpc-tools", ">= 1.60.0", "< 1.78.2"
