AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - test/expected_output/**/*
    - lib/**/*.pb.rb

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInMultilineCall: true
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
