inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - lib/**/*_pb.rb
    - expected_output/**/*
    - test/gapic/annotations/**/*
    - test/gapic/presenters/**/*
    - test/gapic/*.rb
    - test/test_helper.rb

Metrics/AbcSize:
  Exclude:
    - lib/gapic/model/service/nonstandard_lro_provider.rb
    - lib/gapic/schema/loader.rb
    - test/gapic/schema/**/*_test.rb
    - test/gapic/routing_headers/**/*_test.rb

Metrics/ClassLength:
  Exclude:
    - lib/gapic/presenters/**/*
    - test/gapic/schema/**/*_test.rb
    - test/gapic/routing_headers/**/*_test.rb
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Exclude:
    - lib/gapic/ruby_info.rb
    - lib/gapic/model/service/nonstandard_lro_provider.rb
    - test/gapic/schema/**/*_test.rb
    - test/gapic/routing_headers/**/*_test.rb

Metrics/ModuleLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 15

Style/Documentation:
  Exclude:
    - test/**/*
    - templates/default/helpers/**/*
    - lib/gapic/helpers/**/*

Style/Alias:
  EnforcedStyle: prefer_alias_method
