inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - lib/**/*.pb.rb
    - expected_output/**/*
    - test/gapic/annotations/**/*
    - test/gapic/presenters/**/*
    - test/gapic/*.rb
    - test/test_helper.rb
    - Rakefile

Metrics/AbcSize:
  Exclude:
    - lib/gapic/schema/loader.rb
    - test/gapic/schema/api_test.rb

Metrics/ClassLength:
  Exclude:
    - lib/gapic/presenters/**/*
    - lib/gapic/schema/loader.rb
    - test/gapic/schema/api_test.rb

Metrics/MethodLength:
  Exclude:
    - lib/gapic/ruby_info.rb
    - test/gapic/schema/api_test.rb

Metrics/ModuleLength:
  Exclude:
    - lib/gapic/grpc_service_config/parser.rb

Style/Documentation:
  Exclude:
    - test/**/*
    - templates/default/helpers/**/*
    - lib/gapic/helpers/**/*

Style/Alias:
  EnforcedStyle: prefer_alias_method
