inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - lib/**/*.pb.rb
    - expected_output/**/*
    - test/gapic/annotations/**/*
    - test/gapic/presenters/**/*
    - Rakefile

Metrics/ClassLength:
  Exclude:
    - templates/default/helpers/presenters/**/*

Style/Documentation:
  Exclude:
    - test/**/*
    - templates/default/helpers/**/*

Style/Alias:
  EnforcedStyle: prefer_alias_method
