inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - lib/**/*.pb.rb
    - expected_output/**/*
    - test/gapic/annotations/**/*
    - test/gapic/presenters/**/*
    - test/gapic/*.rb
    - test/test_helper.rb
    - Rakefile

Metrics/AbcSize:
  Exclude:
    - lib/gapic/model/service/nonstandard_lro_provider.rb
    - lib/gapic/schema/loader.rb
    - test/gapic/schema/**/*_test.rb
    - test/gapic/routing_headers/**/*_test.rb

Metrics/ClassLength:
  Exclude:
    - lib/gapic/presenters/**/*
    - lib/gapic/schema/loader.rb
    - test/gapic/schema/**/*_test.rb
    - test/gapic/routing_headers/**/*_test.rb

Metrics/MethodLength:
  Exclude:
    - lib/gapic/ruby_info.rb
    - lib/gapic/model/service/nonstandard_lro_provider.rb
    - test/gapic/schema/**/*_test.rb
    - test/gapic/routing_headers/**/*_test.rb

Metrics/ModuleLength:
  Exclude:
    - lib/gapic/grpc_service_config/parser.rb

Metrics/PerceivedComplexity:
  Exclude:
    - test/gapic/routing_headers/explicit_routing_headers_input_match_test.rb

Style/Documentation:
  Exclude:
    - test/**/*
    - templates/default/helpers/**/*
    - lib/gapic/helpers/**/*

Style/Alias:
  EnforcedStyle: prefer_alias_method
