inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - expected_output/**/*
    - tmp/**/*
    - bin/*
    - test/test_helper.rb

Metrics/AbcSize:
  Exclude:
    - test/gapic/schema/cloud_api_test.rb

Metrics/BlockLength:
  Exclude:
    - .toys.rb
    - '*.gemspec'

Metrics/ClassLength:
  Exclude:
    - test/gapic/schema/cloud_api_test.rb
  Max: 200

Metrics/MethodLength:
  Exclude:
    - test/gapic/schema/cloud_api_test.rb

Style/Documentation:
  Exclude:
    - lib/gapic/presenters/**/*
    - test/**/*
