inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - expected_output/**/*
    - tmp/**/*
    - bin/*
    - Rakefile

Style/Documentation:
  Exclude:
    - lib/gapic/presenters/**/*
    - test/**/*
