AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - expected_output/**/*

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInMultilineCall: true
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Metrics/BlockLength:
  ExcludedMethods: ["describe"]
