steps:
  - name: 'gcr.io/cloud-builders/docker@sha256:40c2fb4fcd0ad51376eef166c2e7b2b40a3508d5776e2bf33db3783ab39d0f2e'
    args: ['build', '--tag=${_IMAGE_URL}:${_VERSION}', '.']

images: ['${_IMAGE_URL}:${_VERSION}']
