steps:
  - name: 'gcr.io/cloud-builders/docker@sha256:680b2a8d18a794c165cf97a3f9476784d5d962e945d424cb40b3e086cde0c284'
    args: ['build', '--tag=${_IMAGE_URL}:${_VERSION}', '.']

images: ['${_IMAGE_URL}:${_VERSION}']
