# frozen_string_literal: true

# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "bundler/gem_tasks"
require "rubocop/rake_task"
require "rake/testtask"
require_relative "../shared/gem_defaults"

RuboCop::RakeTask.new # Configuration is in .rubocop.yml
Rake::TestTask.new :test do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

desc "Run the CI build"
task :ci do
  puts "\nBUILDING gapic-generator-cloud\n"
  puts "\ngapic-generator-cloud rubocop\n"
  Rake::Task[:rubocop].invoke
  puts "\ngapic-generator-cloud test\n"
  Rake::Task[:test].invoke
end

desc "Generate the expected output for tests"
task :gen do
  Rake::Task["gen:templates"].invoke
end
namespace :gen do
  desc "Generate the expected output for template tests"
  task :templates do
    generate_cloud_templates :language_v1
    generate_cloud_templates :language_v1beta1
    generate_cloud_templates :language_v1beta2
    generate_cloud_templates :secretmanager_v1beta1
    generate_cloud_templates :speech_v1
    generate_cloud_templates :vision_v1
    generate_cloud_templates :noservice
  end
end

desc "Start an interactive shell."
task :console do
  require "irb"
  require "irb/completion"
  require "pp"

  $LOAD_PATH.unshift "lib"

  ARGV.clear
  IRB.start
end

desc "Build the docker image."
task :image, :name do |_t, args|
  image_name = args[:name] || "ruby-gapic-generator-cloud"
  sh "docker build -t #{image_name} ."
end
namespace :image do
  desc "Build the docker image using the local base image code"
  task :local, :name do |_t, args|
    image_name = args[:name] || "ruby-gapic-generator-cloud"
    prepare_embedded_gapic_generator_directory
    sh "docker build -t #{image_name} ."
    rm_r base_tmp_dir
  end

  task :release do
    require_relative "lib/gapic/generator/cloud/version.rb"
    version = ENV["RELEASE_VERSION"] || Gapic::Generator::Cloud::VERSION
    match = /^((\d+)\.\d+)\.\d+$/.match version
    raise "Bad version format: #{version}" unless match
    version_minor = match[1]
    version_major = match[2]
    project = ENV["PROJECT_ID"] || "gapic-images"
    image_url = "gcr.io/#{project}/gapic-generator-ruby"
    prepare_embedded_gapic_generator_directory
    sh "gcloud builds submit --project=#{project} --config=cloudbuild.yaml" \
       " --substitutions=_IMAGE_URL=#{image_url},_VERSION=#{version} ."
    sh "gcloud container images add-tag --quiet #{image_url}:#{version}" \
       " #{image_url}:#{version_minor} #{image_url}:#{version_major} #{image_url}:latest"
  end
end

def prepare_embedded_gapic_generator_directory
  FileUtils.mkdir_p "tmp"
  base_source_dir = File.join File.dirname(__dir__), "gapic-generator"
  base_tmp_dir = File.join __dir__, "tmp", "gapic-generator"
  FileUtils.rm_rf base_tmp_dir
  FileUtils.cp_r base_source_dir, base_tmp_dir
end

def generate_cloud_templates service
  require "fileutils"
  require "gapic/generators/cloud_generator"

  target_path = File.expand_path File.join("expected_output", String(service))
  FileUtils.rm_rf target_path
  FileUtils.mkdir_p target_path

  protoc_cmd = [
    "grpc_tools_ruby_protoc",
    "-I ../shared/api-common-protos",
    "-I ../shared/googleapis",
    "-I ../shared/protos",
    "--ruby_gapic_opt=generator=cloud",
    "--ruby_out=#{target_path}/lib",
    "--grpc_out=#{target_path}/lib",
    "--ruby_gapic_out=#{target_path}",
    "--ruby_gapic_opt=configuration=../shared/config/#{service}.yml"
  ]

  # Add optional samples paths
  samples = samples_for service
  protoc_cmd << "--ruby_gapic_opt='samples=#{samples.join ';'}'" if samples

  # Add the proto files
  protos = protos_for service
  protoc_cmd << protos.join(" ")

  protoc_cmd = protoc_cmd.join " "
  puts protoc_cmd if ENV["VERBOSE"]

  protoc_cmd_output = `#{protoc_cmd}`
  puts protoc_cmd_output if ENV["VERBOSE"]
end

task default: :ci
