name: CI gapic-common
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  MT_COMPAT: true

jobs:
  CI:
    if: ${{ github.repository == 'googleapis/gapic-generator-ruby' }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ruby: "2.7"
            task: test
          - os: ubuntu-latest
            ruby: "3.0"
            task: test
          - os: ubuntu-latest
            ruby: "3.1"
            task: test
          - os: ubuntu-latest
            ruby: "3.2"
            task: ci
          - os: macos-latest
            ruby: "3.2"
            task: test
          - os: windows-latest
            ruby: "3.2"
            task: test
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Install dependencies
      shell: bash
      run: |
        gem install --no-document toys bundler
        cd gapic-common && bundle install
    - name: Run ${{ matrix.task }}
      shell: bash
      run: |
        cd gapic-common && toys ${{ matrix.task }}
